
   $(document).ready(function(){
        $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
		  
		$(".GCLM1").show();
		$(".GCLM2").hide();
		$(".GCLM3").hide();
		$(".GCLM4").hide();
		$(".GCLM5").hide();
		$(".GCLM6").hide();
		$(".GCLM7").hide();

    // Tabs
	  $("#GCTab1").click(function(){
        $(".GCLM1").show();
		$(".GCLM2").hide();
		$(".GCLM3").hide();
		$(".GCLM4").hide();
		$(".GCLM5").hide();
		$(".GCLM6").hide();
		$(".GCLM7").hide();
         
    });
	
	 $("#GCTab2").click(function(){
        $(".GCLM1").hide();
		$(".GCLM2").show();
		$(".GCLM3").hide();
		$(".GCLM4").hide();
		$(".GCLM5").hide();
		$(".GCLM6").hide();
		$(".GCLM7").hide();
    });
       

	$("#GCTab3").click(function(){
        $(".GCLM1").hide();
		$(".GCLM2").hide();
		$(".GCLM3").show();
		$(".GCLM4").hide();
		$(".GCLM5").hide();
		$(".GCLM6").hide();
		$(".GCLM7").hide();
    });
	   
	// Video Tabs
    $("#GCVideo1But").click(function(){
       $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
         $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video4C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
    
	$("#GCVideo2But").click(function(){
        $(".GCVideo1").hide();
        $(".GCVideo2").show();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video4C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });

	$("#GCVideo3But").click(function(){
        $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").show();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video4C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });

	$("#GCVideo4But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").show();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo5But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").show();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo6But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").show();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo7But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").show();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo8But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").show();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo9But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").show();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo10But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").show();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo11But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").show();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo12But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").show();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	
	$("#GCVideo13But").click(function(){
         $(".GCVideo1").hide();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").show();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo4But").click(function(){
         $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo4But").click(function(){
         $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo4But").click(function(){
         $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo4But").click(function(){
         $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo4But").click(function(){
         $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo4But").click(function(){
         $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
	$("#GCVideo4But").click(function(){
         $(".GCVideo1").show();
        $(".GCVideo2").hide();
        $(".GCVideo3").hide();
        $(".GCVideo4").hide();
		$(".GCVideo5").hide();
        $(".GCVideo6").hide();
        $(".GCVideo7").hide();
        $(".GCVideo8").hide();
		$(".GCVideo9").hide();
        $(".GCVideo10").hide();
        $(".GCVideo11").hide();
        $(".GCVideo12").hide();
		$(".GCVideo13").hide();
		$(".GCVideo14").hide();
		$(".GCVideo15").hide();
		$(".GCVideo16").hide();
		$(".GCVideo17").hide();
		$(".GCVideo18").hide();
		$(".GCVideo19").hide();
		$(".GCVideo20").hide();
		$(".GCVideo21").hide();
		$(".GCVideo22").hide();
		$(".GCVideo23").hide();
		$(".GCVideo24").hide();
		$(".GCVideo25").hide();
		$(".GCVideo26").hide();
		$(".GCVideo27").hide();
		$(".GCVideo28").hide();
		$(".GCVideo29").hide();
		$(".GCVideo30").hide();
 $('#Video1C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video2C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
 $('#Video3C')[0].contentWindow.postMessage('{"event":"command","func":"' + 'pauseVideo' + '","args":""}', '*');  
    });
	
});
